### ISSUE TITLE
I can't train thai language.

### ISSUE THREAD

**Issue by wannaphongcom** [google/language-resources#25]
I build a thai text to speech. I found issue. `$ ./festival_utils/build_festvox_voice.sh ${WAV_FOLDER} th ${OUTPUT_VOICE_FOLDER} > log.txt`

Log : https://gist.github.com/wannaphongcom/aa60b952f6913364b3f55f823ec297a8

**Comment by pasindud** [comment]
hmm seems that you might not have setup the festvox environment properly.

Try following this [1] again

1 - https://github.com/google/language-resources/tree/master/si/festvox#festvox-environment

**Comment by wannaphongcom** [comment]
@pasindud It not working.

Log https://gist.github.com/wannaphongcom/e08b4a371ef43412cbc39b5b549b8d39

**Comment by wannaphongcom** [comment]
@pasindud  Is it possible because of the installation problem?

Install log https://gist.github.com/wannaphongcom/3bde3d1d12512adfc9b81faaa1414eeb

**Comment by pasindud** [comment]
Yes it is a installation problem

**Comment by wannaphongcom** [comment]
@pasindud http://tts.speech.cs.cmu.edu/awb/sptk/SPTK-3.6.tar.gz  Not found.

**Comment by pasindud** [comment]
oh ok, Try
https://download.sourceforge.net/project/sp-tk/SPTK/SPTK-3.6/SPTK-3.6.tar.gz

**Comment by wannaphongcom** [comment]
@pasindud  It's not working. https://gist.github.com/wannaphongcom/dba227ee8c835a0c8d6e87a0a9323ea7

**Comment by pasindud** [comment]
Seems there is still a issue with installation 
because

```
/home/tontan/festival/build/festvox/src/ehmm/bin/FeatureExtraction: No such file or directory
```

FYI we have a docker image here https://hub.docker.com/r/langtech/base-festival

**Comment by wannaphongcom** [comment]
@pasindud  I found a problem. Not found in lexicon but have words in lexicon. https://gist.github.com/wannaphongcom/7af873d5a489bce8cf3eb8494ec3eae9

**Comment by pasindud** [comment]
Check whether the lexicon is sorted and uniq

Try the lexicon by 
```
bash> festival
> (lex.set.compile.file "/path/to/lexicon.scm")
> (lex.lookup "<word to lookup for testing>")
```

**Comment by wannaphongcom** [comment]
@pasindud I try lexicon but It's show nil.

```
festival> (lex.set.compile.file "th/festvox/lexicon.scm")
"th/festvox/lexicon.scm"
festival> (lex.lookup "คน")
("คน" nil nil)
festival> (lex.lookup "คน")
("คน" nil nil)
```

lexicon.scm https://github.com/wannaphongcom/tts-thai/blob/master/festvox/lexicon.scm

**Comment by wannaphongcom** [comment]
@pasindud  Now,  It works  but I could not train.It has error.

Log https://gist.github.com/wannaphongcom/d633ad7af65cd7d18862c4cae8b2edf6

**Comment by pasindud** [comment]
What was the issue with the lexicon ?

Some letter is still not in the lexicon.
```
LEXICON: Word ด์ (plus features) not found in lexicon 
```

Can you post the festvox/___phoneset.scm

**Comment by wannaphongcom** [comment]
@pasindud Do you mean phonology.json? https://github.com/wannaphongcom/tts-thai/blob/master/th/festvox/phonology.json

**Comment by wannaphongcom** [comment]
@pasindud last train https://gist.github.com/wannaphongcom/c82d73ee9f1fac0a77eeb34cfb048247

**Comment by pasindud** [comment]
No, when you run the build script it creates a festvox folder, there is a file called festvox/___phoneset.scm in it

**Comment by wannaphongcom** [comment]
@pasindud ok. https://gist.github.com/wannaphongcom/66d26af7bfc648ca4e9278675d91143e

**Comment by wannaphongcom** [comment]
@pasindud Now, I trained it successfully but It has error when try synthesize one example sentence.

```
# echo 'สวัสดี ทดสอบ ระบบ' |${FESTIVALDIR}/bin/text2wave \
>  -eval festvox/goog_th_unison_cg.scm \
>  -eval '(voice_goog_th_unison_cg)' example.wav

SIOD ERROR: could not open file example.wav
```

Train log : https://gist.github.com/wannaphongcom/07af6593577cdba7679e7dc50c0b50b3

**Comment by wannaphongcom** [comment]
@pasindud  Now, I found solution. I add `-o` to parameters.

```
echo 'สวัสดี ทดสอบ ระบบ' |${FESTIVALDIR}/bin/text2wave \
> -eval festvox/goog_th_unison_cg.scm \
> -eval '(voice_goog_th_unison_cg)' -o example.wav
```
audio : https://soundcloud.com/j5muzwuozouf/hello-tts

Thank you @pasindud
```
echo ขอบคุณ ครับ กูเกิล' |${FESTIVALDIR}/bin/text2wave \
> -eval festvox/goog_th_unison_cg.scm \
> -eval '(voice_goog_th_unison_cg)' -o thank_you_google.wav
```

audio : https://soundcloud.com/j5muzwuozouf/thank-you-google

Thank you Google!

**Comment by pasindud** [comment]
Good job 
One more suggestion, check the sample rate of your audio, if it is not 16000, resample them to be 16000 and train again.
