### ISSUE TITLE
How to make predictions using python code

### ISSUE THREAD

**Issue by birolkuyumcu** [google/language-resources#28]
is three a  any way  using pretraned models at [here](https://github.com/google/transliteration) ?
only command line usage example given
How to make predictions using python code ?

**Comment by pasindud** [comment]
I think this question should be posted in https://github.com/google/transliteration

**Comment by birolkuyumcu** [comment]
"How to use the trained models
The binary clstmfilter can be used to use an already existing model to transliterate your data.

To build the binary, use the command"
i asked how to translate with python
