### ISSUE TITLE
How did you generate 'universal_depot.far' file?

### ISSUE THREAD

**Issue by onchiptech** [google/language-resources#29]
Just wanted to understand how the 'universal_depot.far' file has been created?
Where are the .grm file for all those FSTs in the 'universal_depot.far'  file?

Thank you,
Surendra

**Comment by pasindud** [comment]
The .grm files are not in the far file and they haven't been opensourced yet.

**Comment by onchiptech** [comment]
Thank you,
Is there a document explaining each rule/fst in 'universal_depot.far' file?

**Comment by pasindud** [comment]
So unfortunately we don't have a document like that, what you might be able to do is refer to the names of the rules in [1] (to get some idea)

1 - https://github.com/google/language-resources/blob/master/su/textnorm/verbalizer/universal_rules.grm
