### ISSUE TITLE
Why 'markup' pattern in .tsv files

### ISSUE THREAD

**Issue by onchiptech** [google/language-resources#30]
I see many .tsv files containing following text for example in Sundanese: 
CARDINAL_MARKUP	cardinal|integer:-1|	mineus hiji

And also the .grm files have corresponding grammar definitions to parse these patterns in .tsv files.
Where are these patterns "cardinal|integer:-1|" useful in real world text normalisation?
Why not .grm files just export rules to parse real world examples like "-1"	instead of markup?

**Comment by pasindud** [comment]
If you are referring to [1], it is testdata we use to test the grammars and not used in the actually grm.

1 - https://github.com/google/language-resources/blob/master/su/textnorm/verbalizer/testdata/cardinal.tsv
