### ISSUE TITLE
Error while trying to build prompts for Tamil language

### ISSUE THREAD

**Issue by priyanthini** [google/language-resources#32]
In my lexicon file, words are in the format as follows
("அ" nil (((a) 1)))
I'm actually trying to build Tamil voices using festival.
But when I'm trying to build prompts using " **./bin/do_build $PARALLEL build_prompts** " , it gives errors as " **ta_1566 PROMPTS
LEXICON: Word ஆண்டாள் (plus features) not found in lexicon** " for all the sentences in txt.done.data file.
But all those words are in my lexicon.scm file. How to get over with this error?

**Comment by pasindud** [comment]
The lexicon is probably not sorted correctly.

Though we have open sourced a Tamil dataset, we don't have festival recipes for Tamil
