### ISSUE TITLE
.grm file

### ISSUE THREAD

**Issue by Rajan-sust** [google/language-resources#33]
In [1], all files are written in .grm file. @pasindud is there any official documentation for learning grm.  Because, I wanna contribute to Bn Text Normalization. Is it a compiler design language?

[1] https://github.com/google/language-resources/tree/master/bn/textnorm

**Comment by pasindud** [comment]
To start you can follow the documentation here 
http://www.openfst.org/twiki/bin/view/GRM/Thrax it will guide you through the thrax language

**Comment by Rajan-sust** [comment]
Thanks, @pasindud.

**Comment by pasindud** [comment]
:+1:
