### ISSUE TITLE
Can this python script "generate_hts_questions.py" be used for other languages?

### ISSUE THREAD

**Issue by priyanthini** [google/language-resources#36]
Hi,
I want to create a question file for Tamil language. Can I use the "generate_hts_questions.py" given here, to produce a question file for Tamil language?

**Comment by pasindud** [comment]
Yes you can as long as you have a [1](https://github.com/google/language-resources/blob/master/si/festvox/ipa_phonology.json) the format is described [2](https://github.com/google/language-resources/blob/master/docs/JSON_PHONOLOGY.md)

1 - https://github.com/google/language-resources/blob/master/si/festvox/ipa_phonology.json
2 - https://github.com/google/language-resources/blob/master/docs/JSON_PHONOLOGY.md

**Comment by priyanthini** [comment]
@pasindud Thank you for your reply.
