### ISSUE TITLE
speaker level annotation in the speech datasets

### ISSUE THREAD

**Issue by zabir-nabil** [google/language-resources#47]
Crowdsourced high-quality multi-speaker speech data sets, I see there are line_index_{gender}.tsv file.

In the tsv files, I can see the following data,

```
guf_03209_00443170675	જગતમાં કોઈ જીવ ન્નસ જંગમ છે અને કોઈ સ્થાવર.
guf_01414_00718082800	ગામમાં ભગવાન સ્વામિનારાયણનું મંદિર છે
```

Here, what are 03209 and 00443170675 for the first sample? Are they speaker and utterance id?

**Comment by zabir-nabil** [comment]
ref: https://www.openslr.org/78/

**Comment by agutkin** [comment]
The letter `f` in `guf` means female, the five digit number is the speaker ID, the second 11-digit number is an utterance hash. Please take a look at this [paper](https://aclanthology.org/2020.lrec-1.800/).

**Comment by agutkin** [comment]
Hope this answers your question.
